version: '3'

services:  
  etherpad-db:
    image: mariadb:latest
    container_name: ${ETHERPAD_MYSQL_HOST}
    restart: always
    ports:
      - "${ETHERPAD_MYSQL_PORT}:3306"
    volumes:
      - /srv/data/etherpad/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${ETHERPAD_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${ETHERPAD_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${ETHERPAD_MYSQL_USER}
      MYSQL_PASSWORD: ${ETHERPAD_MYSQL_PASSWORD}

  etherpad:
    build: .
    depends_on:
      - etherpad-db
    image: tabroughton/ethepad-hashed
    container_name: etherpad
    restart: unless-stopped
    ports:
      - "9001:9001"
    environment:
      VIRTUAL_HOST: jotter.tombroughton.me
      VIRTUAL_PORT: 9001
      LETSENCRYPT_HOST: jotter.tombroughton.me
      LETSENCRYPT_EMAIL: hello@tombroughton.me
      ETHERPAD_VERSION: master
      NODE_ENV: production
      ETHERPAD_ADMIN_HASH: "${ETHERPAD_ADMIN_HASH}"
      MYSQL_HOST: ${ETHERPAD_MYSQL_HOST}
      MYSQL_DATABASE: ${ETHERPAD_MYSQL_DATABASE}
      MYSQL_PORT: ${ETHERPAD_MYSQL_PORT}
      MYSQL_USER: ${ETHERPAD_MYSQL_USER}
      MYSQL_PASSWORD: ${ETHERPAD_MYSQL_PASSWORD}
      
networks:
  default:
    external:
      name: nginx-proxy
