version: '3'

services:
  etherpad:
    image: tabroughton/etherpad-alpine
    container_name: etherpad
    restart: unless-stopped
    ports:
      - "9001:9001"
    environment:
      VIRTUAL_HOST: "jotter.tombroughton.me"
      VIRTUAL_PORT: "9001"
      LETSENCRYPT_HOST: "jotter.tombroughton.me"
      LETSENCRYPT_EMAIL: "hello@tombroughton.em"
      ETHERPAD_ADMIN_PASSWORD: "changeme"
# make sure you change the admin password env
      

networks:
  default:
    external:
      name: nginx-proxy
