################################################################
# Entrypoints configuration
################################################################

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

################################################################
# Traefik logs configuration
################################################################

loglevel = "DEBUG"

[retry]

################################################################
# Docker Provider
################################################################

[docker]

endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
swarmMode = false
network = "web"

###########################################################
#  Acme provider
# Enable ACME (Let's Encrypt): automatic SSL.
##########################################################

[acme]

# uncomment and replace email before using in production
#email = "your-email-here@my-awesome-app.org"
storage = "acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
KeyType = "RSA4096"
[acme.httpChallenge]
entryPoint = "http"
